import { baseApiSlice } from "../api/baseApiSlice";

//query endpoints are used for querying data and mutation endpoints are for mutating data on server
//mutation can revalidate cache

export const authApiSlice = baseApiSlice.injectEndpoints({
	endpoints: (builder) => ({
		registerUser: builder.mutation({
			query: (userData) => ({
				url: "/auth/register",
				method: "POST",
				body: userData,
			}),
		}),
	}),
});

export const { useRegisterUserMutation } = authApiSlice;

//this hook is generated by rtk saving my ass
